# Generated by Django 3.1.6 on 2021-02-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('buyer_reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DevolutionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DevolutionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DevolutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DevolutionProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order_product', models.IntegerField()),
                ('id_devolution', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='devolution.devolution')),
                ('id_devolution_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='devolution.devolutionstatus')),
            ],
        ),
        migrations.AddField(
            model_name='devolution',
            name='id_devolution_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='devolution.devolutionreason'),
        ),
        migrations.AddField(
            model_name='devolution',
            name='id_devolution_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='devolution.devolutionstatus'),
        ),
        migrations.AddField(
            model_name='devolution',
            name='id_devolution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='devolution.devolutiontype'),
        ),
    ]
